title: Guillermo Sahonero
description: MRI Researcher, Software Developer & Educator.
url: "https://gsahonero.github.io"
baseurl: ""

# Google Analytics
google_analytics: G-2HP9X9RKJV

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag